name: shedule_test
description: "A new Flutter project."
publish_to: "none"
version: 1.0.1

environment:
  sdk: ^3.9.2

dependencies:
  date_picker_timeline: ^1.2.7
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.1
  get_it: ^8.2.0
  google_fonts: ^7.0.0
  http: ^1.6.0
  icons_launcher: ^3.0.3
  internet_connection_checker_plus: ^2.9.0
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.3
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
icons_launcher:
  image_path: "assets/icons/norm.png"
  platforms:
    android:
      enable: true
      image_path: "assets/icons/norm.png"
      notification_image: "assets/icons/norm.png"
      # adaptive_background_color: '#ffffff'
      adaptive_background_image: "assets/icons/back.png"
      adaptive_foreground_image: "assets/icons/fore.png"
      adaptive_round_image: "assets/icons/round.png"
      adaptive_monochrome_image: "assets/icons/norm.png"
    ios:
      enable: true
      image_path: "assets/icons/norm.png"
      # For iOS 18+ (support dark and tinted)
      dark_path: "assets/icons/norm.png"
      tinted_path: "assets/icons/norm.png"
    web:
      enable: true
      image_path: "assets/icons/norm.png"
      favicon_path: "assets/icons/norm.png"
